Adjusted contract to compile under solidity 0.4.24-0.5.x and truffle 5
gnosis/solidity-arithmetic pull request #2
Opened 2019-02-08 21:25 UTC by alexhulbert

Because the solidity version was prefixed with `^`, the contract was not compiling even when used as a library under Truffle 5. Under truffle 4, several compiler warnings were also being displayed. I've resolved these warnings and pinned both contracts to Solidity version 0.4.24.

2019-04-10 15:46 UTC, cag requested changes
Thanks for your interest, and so sorry I took so long to notice this! It's been a while since I looked at this stuff...

2019-04-10 15:46 UTC, cag commented on contracts/Arithmetic.sol
> +pragma solidity 0.4.24;
Have you tried `pragma solidity >=0.4.24 <0.6.0;`? I think that should work for all of 0.4.24-0.5.x, whereas this pragma pins the source to 0.4.24.

2019-04-10 15:46 UTC, cag commented on contracts/Arithmetic.sol
> +        pure public
This was written a long time ago before I knew about the difference between `public` and `internal` functions on a library. With that said, I'm wondering if this would function better as a "linked" library (like how it is now) or an "inline" library. Dunno if you have any thoughts on the matter (unfortunately, this code doesn't really have users that I'm aware of).

2019-04-18 01:26 UTC, alexhulbert commented on contracts/Arithmetic.sol
> +pragma solidity 0.4.24;
Just tested the contract on 0.4.24, 0.5.1, and 0.5.6. All three work as expected, so I think it's safe to make this change.

2019-04-18 01:29 UTC, alexhulbert commented on contracts/Arithmetic.sol
> +        pure public
You're right. Based on all the other libraries I've looked at, `internal pure` seems to be the idiomatic way to do it.

2019-04-18 01:31 UTC, alexhulbert commented
Should be ready to merge! :+1:

2019-04-19 05:12 UTC, cag approved these changes
Awesome, thanks!

2019-04-19 05:12 UTC, merged